# Data Preprocessing Tools

## Importing the libraries

In [18]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

## Importing the dataset

In [19]:
dataset = pd.read_csv("Data.csv")
x = dataset.iloc[:, :-1].values # "iloc" significa "Index Locate" usamos el rango vacio para tener todas las columnas. Luego restamos 1 para evitar la ultima columna.
y = dataset.iloc[-1].values # no usamos un rango porque buscamos solo una columna.

## Taking care of missing data

In [20]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values=np.nan, strategy='mean')
imputer.fit(x[:, 1:2])
x[:, 1:2] = imputer.transform(x[:, 1:2]) # reemplazamos los valores faltantes por los nuevos valores

## Encoding categorical data

In [21]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [0])], remainder='passthrough')
ct.fit_transform(x)
x = np.array(ct.fit_transform(x))
print(x)

[[1.0 0.0 0.0 44.0 72000.0]
 [0.0 0.0 1.0 27.0 48000.0]
 [0.0 1.0 0.0 30.0 54000.0]
 [0.0 0.0 1.0 38.0 61000.0]
 [0.0 1.0 0.0 40.0 nan]
 [1.0 0.0 0.0 35.0 58000.0]
 [0.0 0.0 1.0 38.77777777777778 52000.0]
 [1.0 0.0 0.0 48.0 79000.0]
 [0.0 1.0 0.0 50.0 83000.0]
 [1.0 0.0 0.0 37.0 67000.0]]


### Encoding the Independent Variable

In [23]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y = le.fit_transform(y)
print(y)

TypeError: Encoders require their input argument must be uniformly strings or numbers. Got ['float64', 'str']

### Encoding the Dependent Variable

## Splitting the dataset into the Training set and Test set

## Feature Scaling